### ISSUE TITLE
Provide ways to have multiple pomerium on the same root domain

### ISSUE THREAD

**Issue by victornoel** [pomerium/pomerium#197]
**Is your feature request related to a problem? Please describe.**

I have multiple kubernetes clusters.
So to protect my apps, I need one pomerium on each cluster.
But for consistency reason, I serve all those apps under the same root domain.

The problem with this is that the two pomerium instances thus fight over the cookie and get confused because each of them thinks it is their own. It results in strange situation where users get disconnected and things like that.

Moreover because of things discussed in #181, some cookies are created at the wrong level of the domain (because root domain is incorrectly detected), pomerium starts redirecting in loops to itself and users get confused because of the strange errors.

**Describe the solution you'd like**

To be able to change the name of the cookie used by pomerium (and to be able to specify explicitly the root domain as discussed in https://github.com/pomerium/pomerium/issues/181#issuecomment-504313518.

**Describe alternatives you've considered**

Using the same cookie secret for both pomerium, it seems to work but it's not a correct solution I believe, just a hack.

**Comment by desimone** [comment]
@victornoel are these clusters logically separated (i.e. are the multiple clusters serving the different policy for the different apps and users or are the clusters basically identical?) Do the clusters share a subdomain? Can you walk me through an example?  

I would expect no session conflict if you wanted to run separate pomerium instances on different clusters so long as each cluster had it's own subdomain (where both routes and authenticate endpoints were served from). 

E.g. I would expect the following to work with multiple clusters.

`httpbin.cluster-one.corp.example.com`
`authenticate.cluster-one.corp.example.com`
`httpbin.cluster-two.corp.example.com`
`authenticate.cluster-two.corp.example.com`

But I would expect this situation to fail due to session overlap using different keys (#181 ?) 

`httpbin.cluster-one.corp.example.com`
`httpbin.cluster-two.corp.example.com`
`authenticate.corp.example.com`



> Using the same cookie secret for both pomerium, it seems to work but it's not a correct solution I believe, just a hack.

This may be the best solution if the clusters are identical, but I am likely misinterpreting the issue.

**Comment by victornoel** [comment]
@desimone my use case does involve clusters sharing the same subdomain yes. This could be for example because one is for production and the other integration, you would then get `app1.corp.example.com` on the first and `dev.app1.corp.example.com`, or maybe you would get `app1.dev.corp.example.com`, but they would still share some part of the domain (even though that last one may work I suppose with the current implementation).

Actually, my real use case is that I had to migrate progressively to a second cluster all my apps so they had to keep their DNS of course, hence it is using the same subdomain.

**Comment by victornoel** [comment]
@desimone I was thinking and another perfectly acceptable solution would be for the cluster to share the authentication service (so it would be deployed only on one cluster).

**Comment by desimone** [comment]
@victornoel 
I believe this should then be resolved with #206 so long as your apps all share the same TLD+1 and you configure `CookieDomain` to be the lowest possible domain level shared by all services.

**Comment by victornoel** [comment]
@desimone I'm not clear how this solve the current problem: in the example in the PR, there seems to be only one authenticate and only one authorize service, right? That could make sense, but you still need two proxy service, one per cluster. And also the proxy service on the second cluster must be able to communicate with the authenticate and authorize services from the first one, or something like that...  Does it mean I must expose them on the internet them?

My main problem though is that if they share the cookie, they must share the cookie secret, if not it won't work. And I don't like so much this idea of having only one secret.

**Comment by victornoel** [comment]
@desimone I think I have understood the confusion: the present issue is not about serving two subdomains in one cluster, it is about serving one subdomain in two clusters.
So #206 does not solve it unfortunately...

**Comment by victornoel** [comment]
@desimone any plan to support this use case?

For example I liked the proposition of having a cookie prefix that can be configured at the pomerium instance level.

**Comment by desimone** [comment]
Hi @victornoel

Sorry, I am probably still misinterpreting this issue but in your particular case, I'm leaning towards the best way to support this functionality is to share the cookie secret amongst clusters. 

Because Pomerium stores user sessions at the wildcard domain level (`*.corp.example.com`) and not at the individual route level (`httpbin.corp.example.com`), the trust boundary is also scoped at that level.  

By scoping the cookie at the wild-card level, it allows allows us to do things like not having to re-login for every managed route. For example, if a user logs into `httpbin.corp.example.com` they will be able to use that same session to navigate to `intranet.corp.example.com` assuming of course they the proper authorization. 

But, because we scope the cookie at that level, the user's web client will pass the encrypted session cookie to any route on that subdomain. This is problematic if anything but pomerium is set up to handle those subdomain routes (we should document this better!). Specifically, if the ingress / load balancer is set up to forward traffic to any non-pomerium handlers on that wild-card subdomain, the (still encrypted) user's session could be inadvertently leaked and hijacked. 

In this case however, the concern is that proxy1 doesn't strip the session cookie from proxy2 before being sent to the downstream app (potentially leaking the session to a malicious or compromised downstream app). 

To hopefully make what I'm trying to say more concrete, consider the following:

1. pomerium instance 1 (p1) has a cookie `p1_pomerium` and handles `app1.example.com`
2. pomerium instance 2 (p2) has a cookie `p2_pomerium` and handles `app2.example.com`
3. User (alice) authenticates against both p1 and p2 over the course of her day.
4. Alice visits app2, and inadvertently leaks the contents of `p1_pomerium`. app1 (if malicious or hacked) can then use those credentials to impersonate alice.

**Comment by victornoel** [comment]
@desimone indeed, I didn't think of this side effect at all. You are right, for my use case it is safer to use the same cookie secret!
