### ISSUE TITLE
Accessing Pomerium Metrics Endpoint Causing Pod Memory Spike

### ISSUE THREAD

**Issue by doctor500** [pomerium/pomerium#5378]
## What happened?
Currently, I have a use case where I'm using Pomerium as an Ingress Controller setup in a GKE Cluster. This ingress controller has more than 500+ Ingress manifests configured. I want to set Cloud Monitoring can consume Pomerium Custom Metrics using Google Managed Prometheus, so we decided to set up our managed collection with the following manifests:

```
apiVersion: monitoring.googleapis.com/v1
kind: PodMonitoring
metadata:
  name: pomerium
  namespace: pomerium
spec:
  endpoints:
    - port: metrics
      interval: 30s
      metricRelabeling:
      - action: keep
        regex: "http_client_requests_total"
        sourceLabels: [__name__]
      - action: keep
        regex: "http_server_requests_total"
        sourceLabels: [__name__]
      - action: keep
        regex: "grpc_client_requests_total"
        sourceLabels: [__name__]
      - action: keep
        regex: "grpc_server_requests_total"
        sourceLabels: [__name__]
  selector:
    matchLabels:
      app.kubernetes.io/name: pomerium
``` 

But turns out it causing all of the Pomerium Controller pod memory to increase almost touching pod limit specs (4GB) in our case. I'm observing by sampling the metrics payload size and found that the payload size is having a size for more than 100MB for each call. Even if we increase the interval collection time, the memory spike still happened.

```
root@xxxxx-6zk5478998-wrr5q:/# curl http://pomerium-metrics.pomerium.svc.cluster.local:9090/metrics > sample.txt
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  122M    0  122M    0     0  16.0M      0 --:--:--  0:00:07 --:--:-- 36.1M
```
```
root@xxxxx-6zk5478998-wrr5q:/# ls -lh --block-size=MB sample.txt
-rw-r--r-- 1 root root 128MB Nov 24 07:48 sample.txt
```
 
This is the current pod condition after the curl process is done (monitored using k9s)
<img width="1149" alt="image" src="https://github.com/user-attachments/assets/2170eb7e-c467-49a2-b0c3-ff8ef53a0fa1">

## What did you expect to happen?
I'm looking for assistance/advice on how to optimize the exported metrics so that every time the collector hits the metrics endpoint it will not cause the pod memory spike, it's a big deal because it makes our HPA setup not work well. From my observation so far from the Pomerium documentation, there are no available options to customize the export metrics.

## How'd it happen?

1. Create 500+ Ingress configuration
2. Create a service that hits internal FQDN Pomerium Metrics Endpoint (http://pomerium-metrics.pomerium.svc.cluster.local:9090/metrics)
3. One of the Pomerium Controller pods will spike

## What's your environment like?

- Setup Pomerium as Ingress Controller
- Most of the Ingress Backend service is located in the different GKE clusters. it route using `ExternalService` (https://www.pomerium.com/docs/k8s/ingress.html#external-services)
- The number of `Ingress` manifest for Pomerium is more than 500+ objects
- Pomerium configured with the following specs:
```
        resources:
          limits:
            cpu: "5"
            memory: 4Gi
          requests:
            cpu: 500m
            memory: 3Gi
```
- Pomerium has HPA with the following setup:
```
spec:
  maxReplicas: 18
  metrics:
  - resource:
      name: memory
      target:
        averageUtilization: 80
        type: Utilization
    type: Resource
  minReplicas: 6
```

## What's your config.yaml?

Since it's setup as GKE Controller, this information might be useful: 
Pomerium CRD config
```
apiVersion: ingress.pomerium.io/v1
kind: Pomerium
metadata:
  name: global
spec:
  authenticate:
    url: https://xxxxxxx
  timeouts:
    read: 60m
  secrets: pomerium/bootstrap
  storage:
    postgres:
      secret: pomerium/xxxxxxx-config
```
One of the Ingress config sample
```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    ingress.pomerium.io/allow_public_unauthenticated_access: 'true'
    ingress.pomerium.io/timeout: '60m'
    ingress.pomerium.io/host_rewrite: 'xxxxxxxxxxxxx'
    ingress.pomerium.io/set_request_headers: |
      X-Custom-Header: asdf
      X-Forwarded-Host: xxxxxxxxxxxxx
  name: xxxxxxxxxxxxx
spec:
  ingressClassName: pomerium
  rules:
    - host: xxxxxxxxxx
      http:
        paths:
          - backend:
              service:
                name: qwertyqwertyqwerty
                port:
                  name: http
            path: /xxxxxxxxxxxxx/anotherpath
            pathType: Prefix
          - backend:
              service:
                name: abcabcabcabc
                port:
                  name: http
            path: /
            pathType: Prefix
```

## What did you see in the logs?

no specific logs related to metrics appear

## Additional context

let me know any other information that might help us solve this issue, Thanks!

**Comment by wasaga** [comment]
1. the high memory consumption should be resolved once [https://github.com/pomerium/pomerium/pull/5364](https://github.com/pomerium/pomerium/pull/5364) is merged and propagated to the ingress controller (should be available soon in `main`). 
2. the `http_requests` and `grpc_requests` metric corresponds to internal pomerium status. What you probably need is `envoy_` set of metrics, which are not related to the `Ingress` resources you created. Each Ingress correspond to Envoy `cluster` and you need to choose the stats you want. See [https://www.envoyproxy.io/docs/envoy/latest/operations/stats_overview](https://www.envoyproxy.io/docs/envoy/latest/operations/stats_overview) for more details.

**Comment by felixjingga** [comment]
> 1. the high memory consumption should be resolved once [core/metrics: improve memory usage #5364](https://github.com/pomerium/pomerium/pull/5364) is merged and propagated to the ingress controller (should be available soon in `main`).
> 2. the `http_requests` and `grpc_requests` metric corresponds to internal pomerium status. What you probably need is `envoy_` set of metrics. Each Ingress correspond to Envoy `cluster` and you need to choose the stats you want. See https://www.envoyproxy.io/docs/envoy/latest/operations/stats_overview for more details.

Hi @wasaga , let me chip in into this discussion

I saw the Pull Request, and yes the PR will possibly fix the high memory consumption issue. But it did not fix that the payload is still big (I tested the setup, and with normal traffic, the payload can be up to 20MB). Is there any way we can filter out the needed payload before it being streamed?

Thanks

**Comment by wasaga** [comment]
I think so, yes, I'm just thinking how to better express it. There are so many different metrics. Maybe we need "classes of metrics" - ie "none", "essential", "full".

**Comment by doctor500** [comment]
I do think instead of classifying the metrics, why don't we define the metrics label that we need? as an example let's say the original metrics are like this:

```Prometheus.yaml
# HELP process_open_fds Number of open file descriptors.
# TYPE process_open_fds gauge
process_open_fds{installation_id="",hostname="pomerium-xxxxxxx-yyyyyyy"} 156
# HELP process_virtual_memory_max_bytes Maximum amount of virtual memory available in bytes.
# TYPE process_virtual_memory_max_bytes gauge
process_virtual_memory_max_bytes{installation_id="",hostname="pomerium-xxxxxxx-yyyyyyy"} 1.8446744073709552e+19
# HELP go_goroutines Number of goroutines that currently exist.
# TYPE go_goroutines gauge
go_goroutines{installation_id="",hostname="pomerium-xxxxxxx-yyyyyyy"} 196
# HELP go_memstats_heap_released_bytes Number of heap bytes released to OS. Equals to /memory/classes/heap/released:bytes.
# TYPE go_memstats_heap_released_bytes gauge
go_memstats_heap_released_bytes{installation_id="",hostname="pomerium-xxxxxxx-yyyyyyy"} 2.23223808e+08
# HELP go_info Information about the Go environment.
# TYPE go_info gauge
go_info{version="go1.23.3",installation_id="",hostname="pomerium-xxxxxxx-yyyyyyy"} 1
# HELP go_memstats_heap_sys_bytes Number of heap bytes obtained from system. Equals to /memory/classes/heap/objects:bytes + /memory/classes/heap/unused:bytes + /memory/classes/heap/released:bytes + /memory/classes/heap/free:bytes.
# TYPE go_memstats_heap_sys_bytes gauge
go_memstats_heap_sys_bytes{installation_id="",hostname="pomerium-xxxxxxx-yyyyyyy"} 2.08265216e+09
# HELP go_memstats_stack_inuse_bytes Number of bytes obtained from system for stack allocator in non-CGO environments. Equals to /memory/classes/heap/stacks:bytes.
# TYPE go_memstats_stack_inuse_bytes gauge
go_memstats_stack_inuse_bytes{installation_id="",hostname="pomerium-xxxxxxx-yyyyyyy"} 1.900544e+06
# HELP pomerium_autocert_certificate_next_expires_seconds The next expiration timestamp in seconds.
# TYPE pomerium_autocert_certificate_next_expires_seconds gauge
pomerium_autocert_certificate_next_expires_seconds{installation_id="",hostname="pomerium-xxxxxxx-yyyyyyy"} 0
# HELP pomerium_autocert_certificates_total Number of certificates tracked by autocert.
# TYPE pomerium_autocert_certificates_total gauge
pomerium_autocert_certificates_total{installation_id="",hostname="pomerium-xxxxxxx-yyyyyyy"} 0
# HELP pomerium_envoy_process_start_time_seconds Start time of the process since unix epoch in seconds.
# TYPE pomerium_envoy_process_start_time_seconds gauge
pomerium_envoy_process_start_time_seconds{installation_id="",hostname="pomerium-xxxxxxx-yyyyyyy"} 1.73242153199e+09
# HELP pomerium_grpc_server_requests_total Total grpc Requests
# TYPE pomerium_grpc_server_requests_total counter
pomerium_grpc_server_requests_total{grpc_method="AcquireLease",grpc_server_status="ALREADY_EXISTS",grpc_service="databroker.DataBrokerService",service="pomerium",installation_id="",hostname="pomerium-xxxxxxx-yyyyyyy"} 865
pomerium_grpc_server_requests_total{grpc_method="Check",grpc_server_status="CANCELLED",grpc_service="envoy.service.auth.v3.Authorization",service="pomerium",installation_id="",hostname="pomerium-xxxxxxx-yyyyyyy"} 1
pomerium_grpc_server_requests_total{grpc_method="Check",grpc_server_status="OK",grpc_service="envoy.service.auth.v3.Authorization",service="pomerium",installation_id="",hostname="pomerium-xxxxxxx-yyyyyyy"} 99345
pomerium_grpc_server_requests_total{grpc_method="Check",grpc_server_status="UNKNOWN",grpc_service="envoy.service.auth.v3.Authorization",service="pomerium",installation_id="",hostname="pomerium-xxxxxxx-yyyyyyy"} 1
pomerium_grpc_server_requests_total{grpc_method="Report",grpc_server_status="OK",grpc_service="registry.Registry",service="pomerium",installation_id="",hostname="pomerium-xxxxxxx-yyyyyyy"} 864
pomerium_grpc_server_requests_total{grpc_method="SyncLatest",grpc_server_status="OK",grpc_service="databroker.DataBrokerService",service="pomerium",installation_id="",hostname="pomerium-xxxxxxx-yyyyyyy"} 1
# HELP process_resident_memory_bytes Resident memory size in bytes.
# TYPE process_resident_memory_bytes gauge
process_resident_memory_bytes{installation_id="",hostname="pomerium-xxxxxxx-yyyyyyy"} 2.074669056e+09
# HELP process_start_time_seconds Start time of the process since unix epoch in seconds.
# TYPE process_start_time_seconds gauge
process_start_time_seconds{installation_id="",hostname="pomerium-xxxxxxx-yyyyyyy"} 1.73242153086e+09
# HELP go_gc_duration_seconds A summary of the wall-time pause (stop-the-world) duration in garbage collection cycles.
# TYPE go_gc_duration_seconds summary
go_gc_duration_seconds{installation_id="",hostname="pomerium-xxxxxxx-yyyyyyy",quantile="0"} 0.000104696
go_gc_duration_seconds{installation_id="",hostname="pomerium-xxxxxxx-yyyyyyy",quantile="0.25"} 0.000300197
go_gc_duration_seconds{installation_id="",hostname="pomerium-xxxxxxx-yyyyyyy",quantile="0.5"} 0.000356167
go_gc_duration_seconds{installation_id="",hostname="pomerium-xxxxxxx-yyyyyyy",quantile="0.75"} 0.000404765
go_gc_duration_seconds{installation_id="",hostname="pomerium-xxxxxxx-yyyyyyy",quantile="1"} 0.006223681
go_gc_duration_seconds_sum{installation_id="",hostname="pomerium-xxxxxxx-yyyyyyy"} 0.059343135
go_gc_duration_seconds_count{installation_id="",hostname="pomerium-xxxxxxx-yyyyyyy"} 138
# HELP go_memstats_mcache_sys_bytes Number of bytes used for mcache structures obtained from system. Equals to /memory/classes/metadata/mcache/inuse:bytes + /memory/classes/metadata/mcache/free:bytes.
# TYPE go_memstats_mcache_sys_bytes gauge
go_memstats_mcache_sys_bytes{installation_id="",hostname="pomerium-xxxxxxx-yyyyyyy"} 15600
# HELP go_threads Number of OS threads created.
# TYPE go_threads gauge
go_threads{installation_id="",hostname="pomerium-xxxxxxx-yyyyyyy"} 14
# HELP pomerium_envoy_overload_action_state Current state of envoy overload actions by cgroup
# TYPE pomerium_envoy_overload_action_state gauge
pomerium_envoy_overload_action_state{action_name="disable_http_keepalive",cgroup="/",installation_id="",hostname="pomerium-xxxxxxx-yyyyyyy"} 0
pomerium_envoy_overload_action_state{action_name="reduce_timeouts",cgroup="/",installation_id="",hostname="pomerium-xxxxxxx-yyyyyyy"} 0
pomerium_envoy_overload_action_state{action_name="reset_high_memory_stream",cgroup="/",installation_id="",hostname="pomerium-xxxxxxx-yyyyyyy"} 0
pomerium_envoy_overload_action_state{action_name="shrink_heap",cgroup="/",installation_id="",hostname="pomerium-xxxxxxx-yyyyyyy"} 0
pomerium_envoy_overload_action_state{action_name="stop_accepting_connections",cgroup="/",installation_id="",hostname="pomerium-xxxxxxx-yyyyyyy"} 0
pomerium_envoy_overload_action_state{action_name="stop_accepting_requests",cgroup="/",installation_id="",hostname="pomerium-xxxxxxx-yyyyyyy"} 0
# HELP pomerium_envoy_process_virtual_memory_max_bytes Maximum amount of virtual memory available in bytes.
# TYPE pomerium_envoy_process_virtual_memory_max_bytes gauge
pomerium_envoy_process_virtual_memory_max_bytes{installation_id="",hostname="pomerium-xxxxxxx-yyyyyyy"} -1
# HELP pomerium_config_last_reload_success Returns 1 if last reload was successful
# TYPE pomerium_config_last_reload_success gauge
pomerium_config_last_reload_success{service="all",installation_id="",hostname="pomerium-xxxxxxx-yyyyyyy"} 1
# HELP pomerium_envoy_process_open_fds Number of open file descriptors.
# TYPE pomerium_envoy_process_open_fds gauge
pomerium_envoy_process_open_fds{installation_id="",hostname="pomerium-xxxxxxx-yyyyyyy"} 2030
```

then, I want only gather the following metrics
```prometheus.yaml
# HELP process_virtual_memory_max_bytes Maximum amount of virtual memory available in bytes.
# TYPE process_virtual_memory_max_bytes gauge
process_virtual_memory_max_bytes{installation_id="",hostname="pomerium-xxxxxxx-yyyyyyy"} 1.8446744073709552e+19
# HELP pomerium_autocert_certificate_next_expires_seconds The next expiration timestamp in seconds.
# TYPE pomerium_autocert_certificate_next_expires_seconds gauge
pomerium_autocert_certificate_next_expires_seconds{installation_id="",hostname="pomerium-xxxxxxx-yyyyyyy"} 0
# HELP pomerium_autocert_certificates_total Number of certificates tracked by autocert.
# TYPE pomerium_autocert_certificates_total gauge
pomerium_autocert_certificates_total{installation_id="",hostname="pomerium-xxxxxxx-yyyyyyy"} 0
# HELP pomerium_envoy_process_start_time_seconds Start time of the process since unix epoch in seconds.
# TYPE pomerium_envoy_process_start_time_seconds gauge
pomerium_envoy_process_start_time_seconds{installation_id="",hostname="pomerium-xxxxxxx-yyyyyyy"} 1.73242153199e+09
# HELP process_resident_memory_bytes Resident memory size in bytes.
# TYPE process_resident_memory_bytes gauge
process_resident_memory_bytes{installation_id="",hostname="pomerium-xxxxxxx-yyyyyyy"} 2.074669056e+09
# HELP process_start_time_seconds Start time of the process since unix epoch in seconds.
# TYPE process_start_time_seconds gauge
process_start_time_seconds{installation_id="",hostname="pomerium-xxxxxxx-yyyyyyy"} 1.73242153086e+09
# HELP pomerium_envoy_process_virtual_memory_max_bytes Maximum amount of virtual memory available in bytes.
# TYPE pomerium_envoy_process_virtual_memory_max_bytes gauge
pomerium_envoy_process_virtual_memory_max_bytes{installation_id="",hostname="pomerium-xxxxxxx-yyyyyyy"} -1
# HELP pomerium_config_last_reload_success Returns 1 if last reload was successful
# TYPE pomerium_config_last_reload_success gauge
pomerium_config_last_reload_success{service="all",installation_id="",hostname="pomerium-xxxxxxx-yyyyyyy"} 1
# HELP pomerium_envoy_process_open_fds Number of open file descriptors.
# TYPE pomerium_envoy_process_open_fds gauge
pomerium_envoy_process_open_fds{installation_id="",hostname="pomerium-xxxxxxx-yyyyyyy"} 2030
```

**Comment by doctor500** [comment]
hi there, any updates for this?

**Comment by wasaga** [comment]
Let's get the memory fix merged and see if it fixes the memory usage for you first. 

The suggestion for label filtering also seems reasonable to me let's address it separately though - I'll resume the discussion in a dedicated ticket.

**Comment by wasaga** [comment]
@doctor500 could you please try `pomerium/ingress-controller:main` and see the results for your environment?

**Comment by doctor500** [comment]
Thanks, will try it

**Comment by doctor500** [comment]
@wasaga, when these changes will be included in the next tag version?

**Comment by wasaga** [comment]
@doctor500 

it is unlikely we would make a new release this month, thus some time in January most likely. 

did it solve the problem for you?

**Comment by doctor500** [comment]
@wasaga I see, I'm still not test it yet. I Will give you an update soon on this thread

**Comment by doctor500** [comment]
from my observation so far, with the same managed collection configuration like I describe before. sadly the memory spike is still happened

**Comment by doctor500** [comment]
I think you can consider the label filtering to resolve this issue since we only a few metrics gathered instead of the whole metrics

**Comment by doctor500** [comment]
Hi @wasaga, just want to know about update for this issue. is there any update for this or for label filtering ?

**Comment by wasaga** [comment]
sorry I missed your previous messages.<br><br>It looks like you're running with a lot of pods allocated with small amounts of resources (4GB RAM per your earlier email). You need to run Pomerium with less pods (i.e. 1-2) having more resources allocated to them. If you run in split-mode I also recommend you start using all-in-one (default).

**Comment by doctor500** [comment]
> sorry I missed your previous messages.It looks like you're running with a lot of pods allocated with small amounts of resources (4GB RAM per your original post). You need to run Pomerium with less pods (i.e. 1-2) having more resources allocated to them. If you run in split-mode I also recommend you start using all-in-one (default).

no worries. any recommendations for how much minimum memory to allocate for each pomerium pod? I already used all-in-one mode on this case

**Comment by felixjingga** [comment]
> sorry I missed your previous messages.It looks like you're running with a lot of pods allocated with small amounts of resources (4GB RAM per your original post). You need to run Pomerium with less pods (i.e. 1-2) having more resources allocated to them. If you run in split-mode I also recommend you start using all-in-one (default).

Hi @wasaga , I wonder why with the output size that big and with @doctor500 gives you some proof that the streaming solution does not really solve the memory spike problem, your solution to his problem is the one that I quote? I'm asking to get a clarity on what is the "real problem" here.

**Comment by doctor500** [comment]
Hi @wasaga , is there any other information that may you need for this issue?
