### ISSUE TITLE
services fail to start without authorize URL

### ISSUE THREAD

**Issue by travisgroth** [pomerium/pomerium#786]
## What happened?

When deploying with the current helm chart, `authenticate`, `authorize` and `cache` services crashloop as they are not given the `AUTHORIZE_SERVICE_URL` env var. 

## What did you expect to happen?

Services that do not require `AUTHORIZE_SERVICE_URL` should continue to start without it set.  While it's easy to share a config in a containerized environment we should probably not require options that aren't used by a service.

## How'd it happen?

Bump currently working chart install to `pomerium/pomerium:master`

## What's your environment like?

- Pomerium version (retrieve with `pomerium --version` or `/ping` endpoint): `v0.8.0+f03f579`
- Server Operating System/Architecture/Cloud: docker-for-desktop + helm

## What's your config.yaml?

```config.yaml
# Paste your configs here
# Be sure to scrub any sensitive values
```

## What did you see in the logs?

```logs
2020-05-27T03:05:08.5035954Z panic: runtime error: invalid memory address or nil pointer dereference
2020-05-27T03:05:08.5036301Z [signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x1115dee]
2020-05-27T03:05:08.5036498Z 
2020-05-27T03:05:08.5036688Z goroutine 88 [running]:
2020-05-27T03:05:08.5036879Z github.com/pomerium/pomerium/internal/controlplane.(*Server).buildClusters(0xc000081bd0, 0xc000f09730, 0x33, 0x2322e01, 0x1549f20)
2020-05-27T03:05:08.5037071Z 	/go/src/github.com/pomerium/pomerium/internal/controlplane/xds_clusters.go:31 +0x1ae
2020-05-27T03:05:08.5039056Z github.com/pomerium/pomerium/internal/controlplane.(*Server).buildDiscoveryResponse(0xc000081bd0, 0x22c7251, 0x1, 0xc000973480, 0x33, 0xc000f09730, 0xc000f09138, 0x6113be, 0x101)
2020-05-27T03:05:08.504132Z 	/go/src/github.com/pomerium/pomerium/internal/controlplane/xds.go:48 +0x3b9
2020-05-27T03:05:08.5041585Z github.com/pomerium/pomerium/internal/controlplane.(*Server).streamAggregatedResourcesProcessStep(0xc000081bd0, 0x17a77a0, 0xc00040c8c0, 0xc00037d260, 0xc00037d2c0, 0x0, 0x0)
2020-05-27T03:05:08.5041814Z 	/go/src/github.com/pomerium/pomerium/internal/controlplane/grpc_xds.go:99 +0x6f7
2020-05-27T03:05:08.5042014Z github.com/pomerium/pomerium/internal/controlplane.(*Server).StreamAggregatedResources.func2(0x0, 0x0)
2020-05-27T03:05:08.5042392Z 	/go/src/github.com/pomerium/pomerium/internal/controlplane/grpc_xds.go:39 +0x4e
2020-05-27T03:05:08.5043037Z golang.org/x/sync/errgroup.(*Group).Go.func1(0xc000b4ced0, 0xc000b4cf00)
2020-05-27T03:05:08.5043261Z 	/go/pkg/mod/golang.org/x/sync@v0.0.0-20200317015054-43a5402ce75a/errgroup/errgroup.go:57 +0x59
2020-05-27T03:05:08.5043474Z created by golang.org/x/sync/errgroup.(*Group).Go
2020-05-27T03:05:08.5043674Z 	/go/pkg/mod/golang.org/x/sync@v0.0.0-20200317015054-43a5402ce75a/errgroup/errgroup.go:54 +0x66
```

**Comment by desimone** [comment]
Related https://github.com/pomerium/pomerium/pull/760

**Comment by calebdoxsey** [comment]
I think this should've been fixed with https://github.com/pomerium/pomerium/pull/777.

**Comment by travisgroth** [comment]
@calebdoxsey weird.  I thought I was testing against the newest master as of last night, but you're correct.  That's my mistake.

However, I think we still have the functional issue on `v0.8.0+f03f579`, the error message is just prettier now:

```
{"level":"info","version":"v0.8.0+f03f579","time":"2020-05-27T14:04:55Z","message":"cmd/pomerium"}
{"level":"info","service":"metrics","insecure":true,"addr":":9090","time":"2020-05-27T14:04:55Z","message":"internal/httputil: http server started"}
{"level":"info","port":"43037","time":"2020-05-27T14:04:55Z","message":"gRPC server started"}
{"level":"info","port":"39095","time":"2020-05-27T14:04:55Z","message":"HTTP server started"}
{"level":"debug","service":"envoy","location":"/tmp/.pomerium-envoy/envoy-config.yaml","time":"2020-05-27T14:04:55Z","message":"wrote config file to location"}
{"level":"fatal","error":"error creating authenticate service: authenticate: invalid 'AUTHORIZE_SERVICE_URL': nil url","time":"2020-05-27T14:04:55Z","message":"cmd/pomerium"}
```

**Comment by calebdoxsey** [comment]
I will remove the check in the authenticate service.

However there's also an error in `authorize`:

```json
{"level":"fatal","error":"error creating authorize service: authorize: bad options: invalid 'AUTHENTICATE_SERVICE_URL': nil url","time":"2020-05-27T14:57:25Z","message":"cmd/pomerium"}
```

The authenticate URL is now required in authorize because that's where we do the session refresh. So we'll need to update the helm chart to account for that.

**Comment by travisgroth** [comment]
Closed in #790
